export const boardStart = [
  [
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
  ],
  [
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
  ],
  [
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
  ],
  [
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
  ],
  [
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
  ],
  [
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
  ],
  [
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
  ],
  [
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
    {
      color: "transparent",
      value: 0,
      isRemoving: false,
      id: "01",
      setTargetBlock: (str: string | null) => str,
    },
  ],
];
