export const boardStart = [
  [
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
  ],
  [
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
  ],
  [
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
  ],
  [
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
  ],
  [
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
  ],
  [
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
  ],
  [
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
  ],
  [
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
    { color: "transparent", value: 0, isDragging: false, id: "01", setTargetBlock: (str: string) => str },
  ],
];
